server {
    listen 80;
    server_name 192.168.3.104;

    location /qrcodes/local {
        proxy_pass http://192.168.3.104:8000/qrcodes/local;
    }

    location /qrcodes/remote { 
        proxy_pass http://192.168.3.104:8000/qrcodes/remote;
    }

    location /qrOffices {
        proxy_pass http://192.168.3.104:8000/qrOffices;
    }

    location /client {
        proxy_pass http://192.168.3.104:8000/client;
    }

    location / {
        root /var/www/csf_v2/frontend/dist;
        try_files $uri $uri/ /index.html;
    }

    location /qrcodes/remote/ {
        alias /var/www/csf_v2/backend/qrcodes/remote/;
    }    

    location /qrcodes/local/ {
        alias /var/www/csf_v2/backend/qrcodes/local/;
    }
}

